package protocol;

public enum MessageType {
	REQUEST_SIZE,
	REQUEST_CONSTRUCTUION_DATE,
	REQUEST_CLEAR,
	REQUEST_SHUFFLE,
	REQUEST_ADD,
	REQUEST_FIND,
	REQUEST_REPLACE,
	REQUEST_RETRIEVE,
	REQUEST_REMOVE,
	REQUEST_SORTED
}
